version: 2

project_name: creareview

snapshot:
  version_template: "nightly"

before:
    hooks:
        - go mod tidy
        - go mod verify

builds:
    -   id: creareview
        binary: creareview
        main: ./cmd/creareview
        env:
            - CGO_ENABLED=0
        goos:
            - linux
            - darwin
        goarch:
            - amd64
            - arm64
        flags:
            - -trimpath
        ldflags:
            - -s -w
            - -X github.com/valksor/go-toolkit/version.Version={{.Version}}
            - -X github.com/valksor/go-toolkit/version.Commit={{.ShortCommit}}
            - -X github.com/valksor/go-toolkit/version.BuildTime={{.Date}}

# Binary-only releases (no tarballs)
archives:
    -   id: binaries
        builds: [creareview]
        format: binary
        name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
    name_template: 'checksums.txt'
    algorithm: sha256

# Minisign signing (signs a checksum file only - simpler)
signs:
    -   id: minisign
        cmd: minisign
        signature: "${artifact}.minisig"
        stdin: "{{ .Env.MINISIGN_PASSWORD }}"
        args:
            - "-S"
            - "-m"
            - "${artifact}"
            - "-s"
            - "/tmp/minisign.key"
            - "-x"
            - "${signature}"
        artifacts: checksum

# SBOM generation
sboms:
    -   artifacts: binary
        documents:
            - "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}.sbom.spdx.json"

changelog:
    sort: ""

release:
    # Append changelog to existing release notes (keeps "Full Changelog" link and custom text)
    mode: append
